title:  JIE REN's Homepage
page-top-title: JIE REN
top-section-bg-text: JIE REN's Homepage
# home-subtitle: Sen Li&ensp;|&ensp;李森
home-subtitle: JIE REN
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'

